return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "ansible-language-server",
      "ansible-lint",
      "bash-language-server",
      "gofumpt",
      "gopls",
      "hadolint",
      "json-lsp",
      "lua-language-server",
      "markdownlint",
      "pyflakes",
      "pylint",
      "python-lsp-server",
      "shellcheck",
      "terraform-ls",
      "tflint",
      "typescript-language-server",
      "yaml-language-server",
      "yamllint",
    },
  },
}
